source 'https://rubygems.org'

gem 'cocoapods', '~> 1.16'
gem 'activesupport', '>=6.1.7.5', '< 7.1.0'
gem 'xcodeproj', '~> 1.27'
gem 'nkf' # Ruby 4.0 compatibility: kconv was removed, nkf provides it
