#!/bin/sh
set -e

echo "=== ci_post_clone.sh: Starting ==="

# ------------------------------------------------------------------
# 1. Install Node.js
#    Xcode Cloud macOS runners do not include Node.js by default.
#    Homebrew is the most reliable way to install it.
# ------------------------------------------------------------------
echo "--- Installing Node.js ---"
if ! command -v node &> /dev/null; then
  brew install node@22 2>/dev/null || brew install node 2>/dev/null
fi

# Homebrew installs to /opt/homebrew (arm64) or /usr/local (x86_64)
export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"

if ! command -v node &> /dev/null; then
  echo "ERROR: Failed to install Node.js"
  exit 1
fi

node --version
npm --version

# ------------------------------------------------------------------
# 2. Install npm dependencies
#    The React Native build phases (hermes-engine, RNCore, RNDeps,
#    Generate Specs, FBReactNativeSpec, Bundle React Native code)
#    all require scripts from node_modules/ to exist.
#    Additionally, 97 source file references in the Pods project
#    point into node_modules/ — those targets can't compile otherwise.
# ------------------------------------------------------------------
echo "--- Installing npm dependencies ---"
cd "$CI_PRIMARY_REPOSITORY_PATH"
npm ci

# ------------------------------------------------------------------
# 3. Run CocoaPods install
#    80+ files in ios/Pods/Target Support Files/ contain hardcoded
#    local paths (e.g. /Users/andrewg/Projects/zephyr-weather/...).
#    These were generated by pod install on the local machine and
#    committed to git. On Xcode Cloud the workspace path is
#    /Volumes/workspace/repository/ — so all those paths are wrong.
#
#    Running pod install regenerates every xcconfig, build script,
#    and support file with CI-appropriate absolute paths.
#
#    Note: the Podfile loads Ruby helpers from node_modules/ (lines
#    1-2), which is why npm ci must run before this step.
# ------------------------------------------------------------------
echo "--- Running pod install ---"
cd "$CI_PRIMARY_REPOSITORY_PATH/ios"

# force_ruby_platform ensures native gems (ffi, etc.) are compiled
# for the CI machine's architecture rather than using pre-built
# platform-specific gems from the lockfile.
bundle config set --local force_ruby_platform true 2>/dev/null || true
bundle install
bundle exec pod install

echo "=== ci_post_clone.sh: Complete ==="
